name: Hello word

on:
  push:
      branches: ["**"]

jobs:
  my_first_job: 
      runs-on: "ubuntu-latest"
      steps:
        - name: Hello step
          run: echo "Helo world ! :)"
        - uses: actions/checkout@v4
        - name: List files
          run: ls
        